language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - android-25
    - build-tools-25.0.1
    - extra-android-m2repository

cache: false

before_install:  
  - npm install body-parser cloudant express nano node-gcm
  - sudo apt-get update  

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./client/gradlew; ls -l ./client/gradlew; ./client/gradlew wrapper -v

script:
  - cd ./client/; ./gradlew clean build
