language: android

jdk:
  - openjdk7

android:
  components:

    - android-22
    - build-tools-22.0.1

cache: false
# Use the Travis Container-Based Infrastructure (see #203)
sudo: false

 before_install:  
 - npm install body-parser cloudant express nano node-gcm
 - sudo apt-get update  

install:
  # Ensure Gradle wrapper is executable, download wrapper and show version
  - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
  # Download and show android dependencies
  # - ./gradlew androidDependencies

script:
  - cd ./client/ && ./gradlew clean build connectedCheck
